version: '2.1'

#
# VOLUMES
#

volumes:
  letsencrypt:
  web:
  web_logs:
  mail:
  storage:
  parity:
  minecraft:
  nextcloud:
  gitlab:
  gitlab-runner:
  discourse:
  redis:
  postgres:


#
# NETWORKS
#

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2a01:4f8:221:1405:4::/80
          ip_range: 2a01:4f8:221:1405:4:b0c5::/96


#
# SERVICES
#

services:

  #
  # PUBLIC SERVICES
  #

  webserver:
    container_name: webserver
    build: webserver
    depends_on:
      - nextcloud
      - gitlab
      - discourse
    networks:
      default:
        ipv6_address: 2a01:4f8:221:1405:4::20
    ports:
      - 80:80
      - 443:443
      - 2222:2222
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - web:/var/www:ro
      - web_logs:/var/log/nginx
    restart: unless-stopped

  mailserver:
    container_name: mailserver
    build: mailserver
    ports:
      - 993:993
    volumes:
      - mail:/var/mail
    restart: unless-stopped

  rslsync:
    container_name: rslsync
    build: rslsync
    ports:
      - 14975:14975
      - 127.0.0.1:8888:8888
    volumes:
      - storage:/data
    restart: unless-stopped

  parity:
    container_name: parity
    image: parity/parity:v1.7.0
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 127.0.0.1:8180:8180
      - 127.0.0.1:8545:8545
      - 127.0.0.1:8546:8546
    volumes:
      - parity:/root/.local/share/io.parity.ethereum
    command: --mode active --chain mainnet --unsafe-expose --no-warp --nat extip:188.40.80.208 --no-discovery --allow-ips public --max-pending-peers 10 --pruning archive --ntp-server de.pool.ntp.org:123
    stop_grace_period: 30s
    restart: unless-stopped

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    networks:
      default:
        ipv6_address: 2a01:4f8:221:1405:4::10
    ports:
      - 25565:25565
    volumes:
      - minecraft:/data
    environment:
      EULA: "true"
    restart: unless-stopped

  #
  # BACKEND SERVICES
  #

  nextcloud:
    container_name: nextcloud
    image: wonderfall/nextcloud
    depends_on:
      - postgres
    volumes:
      - nextcloud:/config
      - nextcloud:/data
      - storage:/storage
    restart: unless-stopped

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    depends_on:
      - redis
      - postgres
    volumes:
      - gitlab:/etc/gitlab
      - gitlab:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://developer.zargony.com'
        gitlab_rails['time_zone'] = 'Berlin'
        gitlab_rails['gitlab_email_from'] = 'gitlab@zargony.com'
        gitlab_rails['gitlab_email_display_name'] = 'zargony.com GitLab'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@zargony.com'
        gitlab_rails['gitlab_default_projects_features_issues'] = false
        gitlab_rails['gitlab_default_projects_features_merge_requests'] = false
        gitlab_rails['gitlab_default_projects_features_wiki'] = false
        gitlab_rails['gitlab_default_projects_features_snippets'] = false
        gitlab_rails['gitlab_default_projects_features_builds'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = ENV['DB_PASS']
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.sendgrid.net'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = 'apikey'
        gitlab_rails['smtp_password'] = ENV['SMTP_PASS']
        gitlab_rails['smtp_domain'] = 'zargony.com'
        gitlab_workhorse['listen_network'] = 'tcp'
        gitlab_workhorse['listen_addr'] = '0.0.0.0:8181'
        postgresql['enable'] = false
        redis['enable'] = false
        nginx['enable'] = false
    env_file: ./gitlab.env
    restart: unless-stopped

  discourse:
    container_name: discourse
    build: discourse
    depends_on:
      - postgres
      - redis
    volumes:
      - discourse:/opt/app/public/uploads
    environment:
      DISCOURSE_DB_HOST: postgres
      DISCOURSE_DB_NAME: discourse
      DISCOURSE_DB_USERNAME: discourse
      #DISCOURSE_DB_PASSWORD:
      DISCOURSE_HOSTNAME: cafe.zargony.com
      DISCOURSE_SMTP_ADDRESS: smtp.sendgrid.net
      DISCOURSE_SMTP_PORT: 587
      DISCOURSE_SMTP_DOMAIN: zargony.com
      DISCOURSE_SMTP_USER_NAME: apikey
      #DISCOURSE_SMTP_PASSWORD:
      DISCOURSE_SMTP_AUTHENTICATION: plain
      DISCOURSE_SMTP_ENABLE_START_TLS: 'true'
      DISCOURSE_REDIS_HOST: redis
      DISCOURSE_SERVE_STATIC_ASSETS: 'true'
      #SECRET_TOKEN:
      UNICORN_WORKERS: 3
      UNICORN_SIDEKIQS: 3
    env_file: ./discourse.env
    restart: unless-stopped

  #
  # INTERNAL SERVICES
  #

  redis:
    container_name: redis
    image: redis:3
    volumes:
      - redis:/data
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:9.5
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner
    volumes:
      - gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
