version: '2'

#
# VOLUMES
#

volumes:
  web:
  web_logs:
  mail:
  cloud:
  minecraft:
  nextcloud:
  gitlab:
  redis:
  postgresql:


#
# NETWORKS
#

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 2a01:4f8:100:546f:4::/80
          ip_range: 2a01:4f8:100:546f:4:b0c5::/96


#
# SERVICES
#

services:

  #
  # PUBLIC SERVICES
  #

  webserver:
    container_name: webserver
    build: webserver
    depends_on:
      - gitlab
      - nextcloud
    networks:
      default:
        ipv6_address: 2a01:4f8:100:546f:4::20
    ports:
      - 80:80
      - 443:443
      - 2222:2222
    volumes:
      - web:/var/www:ro
      - web_logs:/var/log/nginx
    restart: unless-stopped

  mailserver:
    container_name: mailserver
    build: mailserver
    ports:
      - 993:993
    volumes:
      - mail:/var/mail
    restart: unless-stopped

  syncthing:
    container_name: syncthing
    image: tianon/syncthing
    ports:
      - 14975:14975
      - 127.0.0.1:8384:8384
    volumes:
      - cloud:/home/user
    restart: unless-stopped

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    networks:
      default:
        ipv6_address: 2a01:4f8:100:546f:4::10
    ports:
      - 25565:25565
    volumes:
      - minecraft:/data
    environment:
      EULA: "true"
    restart: unless-stopped

  #
  # BACKEND SERVICES
  #

  nextcloud:
    container_name: nextcloud
    image: wonderfall/nextcloud
    depends_on:
      - postgresql
    volumes:
      - nextcloud:/config
      - nextcloud:/data
    restart: unless-stopped

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    depends_on:
      - redis
      - postgresql
    volumes:
      - gitlab:/etc/gitlab
      - gitlab:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://developer.zargony.com'
        gitlab_rails['time_zone'] = 'Berlin'
        gitlab_rails['gitlab_email_from'] = 'gitlab@zargony.com'
        gitlab_rails['gitlab_email_display_name'] = 'zargony.com GitLab'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@zargony.com'
        gitlab_rails['gitlab_default_projects_features_issues'] = false
        gitlab_rails['gitlab_default_projects_features_merge_requests'] = false
        gitlab_rails['gitlab_default_projects_features_wiki'] = false
        gitlab_rails['gitlab_default_projects_features_snippets'] = false
        gitlab_rails['gitlab_default_projects_features_builds'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = ENV['DB_PASS']
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.sendgrid.net'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = 'zargony'
        gitlab_rails['smtp_password'] = ENV['SMTP_PASS']
        gitlab_rails['smtp_domain'] = 'zargony.com'
        gitlab_workhorse['listen_network'] = 'tcp'
        gitlab_workhorse['listen_addr'] = '0.0.0.0:8181'
        postgresql['enable'] = false
        redis['enable'] = false
        nginx['enable'] = false
    env_file: ./gitlab.env
    restart: unless-stopped

  #
  # INTERNAL SERVICES
  #

  redis:
    container_name: redis
    image: redis:3
    volumes:
      - redis:/data
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: postgres:9.5
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: unless-stopped
