version: '2'

#
# VOLUMES
#

volumes:
  web:
  web_logs:
  mail:
  cloud:
  minecraft:
  factorio:
  owncloud:
  gitlab:
  redis:
  postgresql:


#
# NETWORKS
#

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 2a01:4f8:100:546f:4::/80
          ip_range: 2a01:4f8:100:546f:4:b0c5::/96


#
# SERVICES
#

services:

  #
  # PUBLIC SERVICES
  #

  webserver:
    container_name: webserver
    build: webserver
    depends_on:
      - gitlab
      - owncloud
    networks:
      default:
        ipv6_address: 2a01:4f8:100:546f:4::20
    ports:
      - 80:80
      - 443:443
      - 2222:2222
    volumes:
      - web:/var/www:ro
      - web_logs:/var/log/nginx
    restart: unless-stopped

  mailserver:
    container_name: mailserver
    build: mailserver
    ports:
      - 993:993
    volumes:
      - mail:/var/mail
    restart: unless-stopped

  syncthing:
    container_name: syncthing
    image: tianon/syncthing
    ports:
      - 14975:14975
      - 127.0.0.1:8384:8384
    volumes:
      - cloud:/home/user
    restart: unless-stopped

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    networks:
      default:
        ipv6_address: 2a01:4f8:100:546f:4::10
    ports:
      - 25565:25565
    volumes:
      - minecraft:/data
    environment:
      EULA: "true"
    restart: unless-stopped

  factorio:
    container_name: factorio
    image: hugecannon/factorio
    command: --disallow-commands --start-server world1
    networks:
      default:
        ipv6_address: 2a01:4f8:100:546f:4::40
    ports:
      - 34197:34197/udp
    volumes:
      - factorio:/factorio/saves
    restart: unless-stopped

  #
  # BACKEND SERVICES
  #

  owncloud:
    container_name: owncloud
    image: owncloud
    depends_on:
      - postgresql
    volumes:
      - owncloud:/var/www/html
    restart: unless-stopped

  gitlab:
    container_name: gitlab
    image: sameersbn/gitlab
    depends_on:
      - redis
      - postgresql
    volumes:
      - gitlab:/home/git/data
    environment:
      GITLAB_HOST: developer.zargony.com
      #GITLAB_SECRETS_DB_KEY_BASE: xxxxx
      GITLAB_TIMEZONE: Berlin
      GITLAB_EMAIL: gitlab@zargony.com
      GITLAB_EMAIL_DISPLAY_NAME: zargony.com GitLab
      GITLAB_PROJECTS_ISSUES: "false"
      GITLAB_PROJECTS_MERGE_REQUESTS: "false"
      GITLAB_PROJECTS_WIKI: "false"
      GITLAB_PROJECTS_SNIPPETS: "false"
      GITLAB_PROJECTS_VISIBILITY: private
      GITLAB_SSH_PORT: 2222
      GITLAB_HTTPS: "true"
      SSL_SELF_SIGNED: "true"
      REDIS_HOST: redis
      DB_ADAPTER: postgresql
      DB_HOST: postgresql
      DB_NAME: gitlab
      DB_USER: gitlab
      #DB_PASS: xxxxx
      SMTP_ENABLED: "true"
      SMTP_DOMAIN: zargony.com
      SMTP_HOST: smtp.sendgrid.net
      SMTP_USER: zargony
      #SMTP_PASS: xxxxx
    env_file: ./gitlab.env
    restart: unless-stopped

  #
  # INTERNAL SERVICES
  #

  redis:
    container_name: redis
    image: redis:3
    volumes:
      - redis:/data
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: postgres:9.4
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: unless-stopped
