FROM sameersbn/gitlab

ENV GITLAB_HOST=developer.zargony.com \
    GITLAB_TIMEZONE=Berlin \
    GITLAB_EMAIL=gitlab@zargony.com \
    GITLAB_EMAIL_DISPLAY_NAME="zargony.com GitLab" \
    GITLAB_PROJECTS_ISSUES=false \
    GITLAB_PROJECTS_MERGE_REQUESTS=false \
    GITLAB_PROJECTS_WIKI=false \
    GITLAB_PROJECTS_SNIPPETS=false \
    GITLAB_PROJECTS_VISIBILITY=private \
    DB_NAME=gitlab \
    DB_USER=gitlab \
    #DB_PASS=xxxxx \
    SMTP_ENABLED=true \
    SMTP_DOMAIN=zargony.com \
    SMTP_HOST=smtp.sendgrid.net \
    SMTP_USER=zargony \
    #SMTP_PASS=xxxxx \
    USERMAP_UID=1283 \
    USERMAP_GID=1283
