#!/bin/bash

try_proxy () {
	if nc -z ${1/:/ }; then
		echo "Using auto-detected proxy: ${1}" >&2
		echo "http://${1}/"
		exit
	fi
}

if grep -q "VBOX HARDDISK" /sys/block/sda/device/model; then
	try_proxy 10.0.2.2:3142
fi
if [ -x /.dockerinit ]; then
	try_proxy 172.17.42.1:3142
fi
